services:
  netalertx:
    image: jokobsk/netalertx:latest
    container_name: netalertx
    restart: always
    network_mode: host
    volumes:
      - ./path/netalertx/config:/app/config
      - ./path/netalertx/db:/app/db
    environment:
      - TZ=${TZ}
      - PORT=${PORT} # 2020