version: '3.2'
services:
    changedetection:
      image: ghcr.io/dgtlmoon/changedetection.io
      container_name: changedetection
      hostname: changedetection
      volumes:
        - ./path/changedetection:/datastore
      environment:
        - PUID=${PUID}
        - PGID=${PGID}
      ports:
        - 5000:5000
      restart: unless-stopped
volumes:
  changedetection-data:
