version: '3'
services:
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Optional, only if you want docker integration
      - ./path:/app/data/configs
      - ./path:/app/public/icons
      - ./path:/data
    ports:
      - '7575:7575'