version: '3.9'

services:
  jellyfin:
    image: jellyfin/jellyfin:latest  
    container_name: jellyfin
    restart: unless-stopped
    network_mode: host
    volumes:
      - ~/config:/config
      - ~/cache:/cache
      - ~/media-jellyfin:/media
