services:
  kavita:
    image: lscr.io/linuxserver/kavita:latest
    container_name: kavita
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ~/config:/config
      - ~/data:/data 
    ports:
      - 5500:5000
    restart: unless-stopped
